version: "3.7"  # optional since v1.27.0
services:
  web:
    image: 'php:7.4-apache'
    restart: always
    ports: 
      - 80:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - banco
    links:
      - banco
  banco:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: joomla